apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-core
  namespace: katib
  labels:
    app: vizier
    component: core
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-core
      labels:
        app: vizier
        component: core
    spec:
      serviceAccountName: vizier-core
      containers:
      - name: vizier-core
        image: katib/vizier-core
        command:
          - './vizier-manager'
        args:
          - "-w"
          - "kubernetes"
          - "-i"
          - "k-cluster.example.net"
        ports:
        - name: api
          containerPort: 6789
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
