apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vizier-earlystopping-medianstopping
  namespace: katib
  labels:
    app: vizier
    component: earlystopping-medianstopping
spec:
  replicas: 1
  template:
    metadata:
      name: vizier-earlystopping-medianstopping
      labels:
        app: vizier
        component: earlystopping-medianstopping
    spec:
      containers:
      - name: vizier-earlystopping-medianstopping
        image: katib/earlystopping-medianstopping
        ports:
        - name: api
          containerPort: 6789
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
