apiVersion: v1
kind: Service
metadata:
  name: vizier-suggestion-hayperband
  namespace: katib
  labels:
    app: vizier
    component: suggestion-hayperband
spec:
  type: ClusterIP
  ports:
    - port: 6789
      protocol: TCP
      name: api
  selector:
    app: vizier
    component: suggestion-hayperband
